import { type Question } from "@/types";

export const mockSubjects = [
    { id: '1', name: 'Anatomy' },
    { id: '2', name: 'Physiology' },
    { id: '3', name: 'Pharmacology' },
];

export const mockChapters = [
    { id: 'c1', name: 'Upper Limb', subjectId: '1' },
    { id: 'c2', name: 'Lower Limb', subjectId: '1' },
    { id: 'c3', name: 'Cardiovascular System', subjectId: '2' },
    { id: 'c4', name: 'Respiratory System', subjectId: '2' },
    { id: 'c5', name: 'Autonomic Nervous System', subjectId: '3' },
];

export const mockQuestions: Question[] = [
  {
    id: "q1",
    questionText: "Which of the following muscles is a primary flexor of the forearm at the elbow joint?",
    options: ["Triceps brachii", "Brachialis", "Anconeus", "Supinator"],
    correctAnswer: "Brachialis",
    explanation: "The brachialis is the primary flexor of the elbow. The biceps brachii is a powerful supinator and flexor, but brachialis is the 'workhorse' of elbow flexion.",
    subject: "Anatomy",
    chapter: "Upper Limb",
    topicTags: ["muscles", "elbow", "flexion"],
    questionType: "mcq",
    difficulty: "easy",
    language: "en",
    source: "Grays Anatomy, 41st Edition",
    createdAt: "2023-10-26T10:00:00Z",
    updatedAt: "2023-10-26T10:00:00Z",
  },
  {
    id: "q2",
    questionText: "True or False: The sinoatrial (SA) node is located in the wall of the left atrium.",
    options: ["True", "False"],
    correctAnswer: "False",
    explanation: "The SA node, the natural pacemaker of the heart, is located in the upper part of the wall of the right atrium.",
    subject: "Physiology",
    chapter: "Cardiovascular System",
    topicTags: ["heart", "conduction system", "SA node"],
    questionType: "tf",
    difficulty: "easy",
    language: "en",
    createdAt: "2023-11-15T14:30:00Z",
    updatedAt: "2023-11-15T14:30:00Z",
  },
  {
    id: "q3",
    questionText: "What is the primary mechanism of action for beta-blockers?",
    explanation: "",
    subject: "Pharmacology",
    chapter: "Autonomic Nervous System",
    topicTags: ["beta-blockers", "adrenergic"],
    questionType: "short",
    difficulty: "medium",
    language: "en",
    createdAt: "2023-09-01T09:00:00Z",
    updatedAt: "2023-09-01T09:00:00Z",
  },
  {
    id: "q4",
    questionText: "أي شريان يزود الدم بشكل أساسي إلى الحجاب الحاجز؟",
    options: ["الشريان الأبهر الصدري", "الشريان الوربي", "الشريان الحجابي السفلي", "الشريان المساريقي العلوي"],
    correctAnswer: "الشريان الحجابي السفلي",
    explanation: "الشريان الحجابي السفلي هو المصدر الرئيسي للدم للحجاب الحاجز.",
    subject: "Anatomy",
    chapter: "Respiratory System",
    topicTags: ["diaphragm", "arterial supply"],
    questionType: "mcq",
    difficulty: "medium",
    language: "ar",
    createdAt: "2024-01-20T11:45:00Z",
    updatedAt: "2024-01-20T11:45:00Z",
  },
   {
    id: "q5",
    questionText: "A 55-year-old patient is prescribed a non-selective beta-blocker for hypertension. Which of the following conditions in their medical history would be a contraindication?",
    options: ["Asthma", "Diabetes Type 2", "Gout", "Hyperlipidemia"],
    correctAnswer: "Asthma",
    explanation: "Non-selective beta-blockers can cause bronchoconstriction by blocking beta-2 receptors in the lungs, which can be dangerous for patients with asthma.",
    subject: "Pharmacology",
    chapter: "Autonomic Nervous System",
    topicTags: ["contraindications", "beta-blockers", "asthma"],
    questionType: "case",
    difficulty: "hard",
    language: "en",
    source: "Katzung & Trevor's Pharmacology",
    createdAt: "2024-02-10T18:00:00Z",
    updatedAt: "2024-02-10T18:00:00Z",
  },
];
